version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db 
    #network_mode: services:[db, redis]

    #:redis

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb 
      MYSQL_PASSWORD: mariadb
  
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    network_mode: service:db

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    network_mode: service:db 
    command:
      --save 120 1
    
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
volumes:
  mariadb-data:
  redis-data:
  mongodb-data:
