version: '3.8'

services: 
  app:  # main development container
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db 

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db: # mariadb container
    image: mariadb:10.4 # image_name:tag from docker hub
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql # persistent data
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb 
      MYSQL_PASSWORD: mariadb
  
  mongodb: # mongodb container
    image: mongodb/mongodb-community-server:latest  # image_name:tag from docker hub
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db # persistent data
    network_mode: service:db  # connect to network run by mariadb container

  redis: # redis container
    image: redis  # image name from docker hub
    restart: unless-stopped
    volumes:
      - redis-data:/data      # persistent data
    network_mode: service:db # connect to network run by mariadb container
    command:
      --save 120 1             # pass --save 120 1 as argument to docker run
    
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
volumes: # list all volumes from above
  mariadb-data:
  redis-data:
  mongodb-data:
